### ISSUE TITLE
MP3-H1 sondes bandwidth

### ISSUE THREAD

**Issue by flux242** [rs1729/RS#34]
Could you tell me what bandwidth have the MP3-H1 sondes? Based on the source code I assume that if baudrate is 2400 and manchester bit encoding is used than they should have at least 5kHz (demodulated) bandwidth. Is that about right? Are there any IQ samples available I could test with?

Thanks

**Comment by rs1729** [comment]
2400 baud is the symbol rate (the bit rate due to Manchester coding would be 1200 bit/s), the symbol rate is what matters.
I didn't check the exact modulation index, but decoding was best with index h=2.0. The spectrum shape also suggests something like that. The two frequency peaks seem to be 4.8kHz apart (see below video, Manchester coding usually shows these dominant frequencies). There is not much pulse shaping.
Here is a short video of a rather weak signal:
https://www.youtube.com/watch?v=oNkX_u5NN4E
With option --IQ it decoded best with IF lowpass bandwidth 8..9 kHz (option --lp bandwidth is set to 9kHz). Same with FM-demodulation like in the video.

**Comment by flux242** [comment]
ok, I've tested the decoder using that video
