### ISSUE TITLE
bch_ecc.c:54:15: error: unknown type name ‘ui8_t’

### ISSUE THREAD

**Issue by joecupano** [rs1729/RS#40]
Per subject. Get error when compiling all on RPi4  4GB RAM

gcc (Raspbian 8.3.0-6+rpi1) 8.3.0
cmake 3.16.3

**Comment by rs1729** [comment]
If you mean `RS/ecc/bch_ecc.c` that was ment to be included in `ecc-rs_vaisala.c`:
```
  gcc init_rs_char.o decode_rs_char.o ecc-rs_vaisala.c -o ecc-rs_vaisala
```
However you would also need the ka9q-fec library, because `ecc-rs_vaisala.c` was for testing and comparing both Reed-Solomon decoders. Without ka9q-fec library, you could comment out the lines
https://github.com/rs1729/RS/blob/master/ecc/ecc-rs_vaisala.c#L10
https://github.com/rs1729/RS/blob/master/ecc/ecc-rs_vaisala.c#L99
https://github.com/rs1729/RS/blob/master/ecc/ecc-rs_vaisala.c#L132
https://github.com/rs1729/RS/blob/master/ecc/ecc-rs_vaisala.c#L157
https://github.com/rs1729/RS/blob/master/ecc/ecc-rs_vaisala.c#L177
https://github.com/rs1729/RS/blob/master/ecc/ecc-rs_vaisala.c#L178
https://github.com/rs1729/RS/blob/master/ecc/ecc-rs_vaisala.c#L219
https://github.com/rs1729/RS/blob/master/ecc/ecc-rs_vaisala.c#L224
and compile:
`gcc ecc-rs_vaisala.c -o ecc-rs_vaisala`
and use it or rs92 or rs41 raw frames like in this:
https://github.com/rs1729/RS/blob/master/ecc/ecc-rs_vaisala.c#L239
or here
https://github.com/rs1729/RS/blob/master/ecc/ecc.txt#L157


If you only want to compile `gcc -c bch_ecc.c`, you could uncomment the two typedefs at
https://github.com/rs1729/RS/blob/master/ecc/bch_ecc.c#L43
and also include `stdio.h`, or you put the defines and the function prototypes in a header file.

However this version of bch_ecc.c is old, I recommend looking at bch_ecc_mod.c/h in
https://github.com/rs1729/RS/tree/master/demod/mod

**Comment by joecupano** [comment]
Apologies for the delay. Thank you
