### ISSUE TITLE
MRZ-H1 uBlox Version

### ISSUE THREAD

**Issue by darksidelemm** [rs1729/RS#51]
Raising this as a placeholder. It appears there is a new version of the MRZ-H1 which uses a uBlox GPS. 
Unsure what the differences in telemetry are, but apparently there is one station with a modified or new decoder (unsure) which is decoding it. Trying to get some more information from them about it.

**Comment by rs1729** [comment]
Have seen "ublox" in the SN on Sondehub yesterday, but don't have any information what it's supposed to mean.

**Comment by darksidelemm** [comment]
Yep, that's the one. I'm as yet unsure as to the extend of what they have had to modify, or how different the telemetry is. Have asked for further information.

**Comment by rs1729** [comment]
BatiaMahno has tear down video from Jan 9th, there is a STM32F373. Wasn't it a F100 before? Don't remember.
There is also a ublox GPS/GLONASS visible I think (5:20). The old antenna looks the same as in the older videos.

Don't know if the data format changed. If they have a STM32 on board, they could convert data from different GPS modules I guess, but who knows.

EDIT
and a video on "MP3 H1 U blox" 10 month ago.
ublox NEO-M8Q
The radiosonde looks different though. There are different versions.  Don't know if this is L band, the radio antenna looks normal.
Or drop sonde? Looks more like MP3-3AK1 which seems to be L band.

"MRZ-H1-UBLOX 12345678" was recorded on the ground. In the video it is at 403MHz.

So I don't know, I only read the numbers, don't understand russian...

**Comment by einergehtnochrein** [comment]
I have the same sonde that is shown in the video, i.e. the same housing and the same components (STM32F373CBT6, ADF7012, NEO-M8Q). Unfortunately there is a serial number, but no indication of the type. I just assume it's the MP3-H1 because that's what I was told...

It's the only MRZ sonde I know, and it is what I used to write my decoder. A quick comparison with the RS code shows it's identical with respect to GPS and PTU data.

One remark on the voltage measurements in the video (I can't resist...): There is a switching regulator to boost the 4.5V battery up to 8V. Then two LDOs generate 5V for the PA and 3.3V for all the rest from that 8V rail! This is the worst design of all sondes I've seen so far.
